import { defineField, defineType } from 'sanity';

export const settings = defineType({
  name: 'settings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'global', title: 'Global', default: true },
    { name: 'homepage', title: 'Homepage' },
    { name: 'about', title: 'About Page' },
    { name: 'contact', title: 'Contact Page' },
    { name: 'footer', title: 'Footer' },
  ],
  fields: [
    // ─── GLOBAL ──────────────────────────────────────────────
    defineField({
      name: 'promptpayNumber',
      title: 'PromptPay Number',
      type: 'string',
      group: 'global',
      description: 'Phone number or national ID used for PromptPay payments',
      validation: (r) => r.required(),
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      group: 'global',
      validation: (r) => r.required().email(),
    }),
    defineField({
      name: 'instagramHandle',
      title: 'Instagram Handle',
      type: 'string',
      group: 'global',
      description: 'Without the @ symbol',
      initialValue: 'akdovey',
    }),
    defineField({
      name: 'location',
      title: 'Location / Venue',
      type: 'string',
      group: 'global',
      description: 'Shown on contact and schedule pages',
    }),
    defineField({
      name: 'announcementBannerEn',
      title: 'Announcement Banner (English)',
      type: 'string',
      group: 'global',
      description: 'Optional — shown at the top of every page when filled in',
    }),
    defineField({
      name: 'announcementBannerTh',
      title: 'Announcement Banner (Thai)',
      type: 'string',
      group: 'global',
    }),
    defineField({
      name: 'registrationsOpen',
      title: 'Registrations Open',
      type: 'boolean',
      group: 'global',
      description: 'Turn off to temporarily disable all registration forms site-wide',
      initialValue: true,
    }),

    // ─── HOMEPAGE ────────────────────────────────────────────
    defineField({
      name: 'heroHeadlineEn',
      title: 'Hero Headline (English)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'heroHeadlineTh',
      title: 'Hero Headline (Thai)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'heroSubheadlineEn',
      title: 'Hero Subheadline (English)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'heroSubheadlineTh',
      title: 'Hero Subheadline (Thai)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'missionTitleEn',
      title: 'Mission Section Title (English)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'missionTitleTh',
      title: 'Mission Section Title (Thai)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({
      name: 'mission1TitleEn',
      title: 'Mission Card 1 — Title (English)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({ name: 'mission1TitleTh', title: 'Mission Card 1 — Title (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission1DescEn', title: 'Mission Card 1 — Description (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission1DescTh', title: 'Mission Card 1 — Description (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission2TitleEn', title: 'Mission Card 2 — Title (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission2TitleTh', title: 'Mission Card 2 — Title (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission2DescEn', title: 'Mission Card 2 — Description (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission2DescTh', title: 'Mission Card 2 — Description (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission3TitleEn', title: 'Mission Card 3 — Title (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission3TitleTh', title: 'Mission Card 3 — Title (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission3DescEn', title: 'Mission Card 3 — Description (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'mission3DescTh', title: 'Mission Card 3 — Description (Thai)', type: 'string', group: 'homepage' }),
    defineField({
      name: 'igSectionTitleEn',
      title: 'Instagram Section — Title (English)',
      type: 'string',
      group: 'homepage',
    }),
    defineField({ name: 'igSectionTitleTh', title: 'Instagram Section — Title (Thai)', type: 'string', group: 'homepage' }),
    defineField({ name: 'igSectionSubtitleEn', title: 'Instagram Section — Subtitle (English)', type: 'string', group: 'homepage' }),
    defineField({ name: 'igSectionSubtitleTh', title: 'Instagram Section — Subtitle (Thai)', type: 'string', group: 'homepage' }),

    // ─── ABOUT PAGE ──────────────────────────────────────────
    defineField({ name: 'aboutHeadlineEn', title: 'Page Headline (English)', type: 'string', group: 'about' }),
    defineField({ name: 'aboutHeadlineTh', title: 'Page Headline (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'aboutSubtitleEn', title: 'Page Subtitle (English)', type: 'string', group: 'about' }),
    defineField({ name: 'aboutSubtitleTh', title: 'Page Subtitle (Thai)', type: 'string', group: 'about' }),
    defineField({
      name: 'bioEn',
      title: 'Founder Bio (English)',
      type: 'text',
      rows: 5,
      group: 'about',
      description: "Shown under Alex's name on the About page.",
    }),
    defineField({ name: 'bioTh', title: 'Founder Bio (Thai)', type: 'text', rows: 5, group: 'about' }),
    defineField({ name: 'whyTitleEn', title: 'Why Section — Title (English)', type: 'string', group: 'about' }),
    defineField({ name: 'whyTitleTh', title: 'Why Section — Title (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why1TitleEn', title: 'Why Card 1 — Title (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why1TitleTh', title: 'Why Card 1 — Title (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why1DescEn', title: 'Why Card 1 — Description (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why1DescTh', title: 'Why Card 1 — Description (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why2TitleEn', title: 'Why Card 2 — Title (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why2TitleTh', title: 'Why Card 2 — Title (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why2DescEn', title: 'Why Card 2 — Description (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why2DescTh', title: 'Why Card 2 — Description (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why3TitleEn', title: 'Why Card 3 — Title (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why3TitleTh', title: 'Why Card 3 — Title (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'why3DescEn', title: 'Why Card 3 — Description (English)', type: 'string', group: 'about' }),
    defineField({ name: 'why3DescTh', title: 'Why Card 3 — Description (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'comingTitleEn', title: '"Coming to Pattaya" — Title (English)', type: 'string', group: 'about' }),
    defineField({ name: 'comingTitleTh', title: '"Coming to Pattaya" — Title (Thai)', type: 'string', group: 'about' }),
    defineField({ name: 'comingDescEn', title: '"Coming to Pattaya" — Body (English)', type: 'text', rows: 3, group: 'about' }),
    defineField({ name: 'comingDescTh', title: '"Coming to Pattaya" — Body (Thai)', type: 'text', rows: 3, group: 'about' }),

    // ─── CONTACT PAGE ────────────────────────────────────────
    defineField({ name: 'contactHeadlineEn', title: 'Page Headline (English)', type: 'string', group: 'contact' }),
    defineField({ name: 'contactHeadlineTh', title: 'Page Headline (Thai)', type: 'string', group: 'contact' }),
    defineField({ name: 'contactSubtitleEn', title: 'Page Subtitle (English)', type: 'string', group: 'contact' }),
    defineField({ name: 'contactSubtitleTh', title: 'Page Subtitle (Thai)', type: 'string', group: 'contact' }),
    defineField({ name: 'locationDescEn', title: 'Location Line 1 (English)', type: 'string', group: 'contact', description: 'e.g. "Coming to Pattaya, Thailand"' }),
    defineField({ name: 'locationDescTh', title: 'Location Line 1 (Thai)', type: 'string', group: 'contact' }),
    defineField({ name: 'locationSubEn', title: 'Location Line 2 (English)', type: 'string', group: 'contact', description: 'e.g. "Exact venue to be announced."' }),
    defineField({ name: 'locationSubTh', title: 'Location Line 2 (Thai)', type: 'string', group: 'contact' }),

    // ─── FOOTER ──────────────────────────────────────────────
    defineField({ name: 'footerTaglineEn', title: 'Tagline (English)', type: 'string', group: 'footer' }),
    defineField({ name: 'footerTaglineTh', title: 'Tagline (Thai)', type: 'string', group: 'footer' }),
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' };
    },
  },
});
